# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tx.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x08tx.proto\"\x17\n\x03Txs\x12\x10\n\x03txs\x18\x01 \x03(\x0b\x32\x03.Tx\"\xbc\x01\n\x02Tx\x12\r\n\x05\x66rom_\x18\x01 \x01(\x0c\x12\n\n\x02to\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x12\x0b\n\x03\x66\x65\x65\x18\x04 \x01(\x04\x12\r\n\x05nonce\x18\x05 \x01(\r\x12\x11\n\tsignature\x18\x06 \x01(\x0c\x12\x10\n\x08recovery\x18\x07 \x01(\r\x12\x1b\n\x13transitionSignature\x18\x08 \x01(\x0c\x12\x1a\n\x12transitionRecovery\x18\t \x01(\r\x12\x11\n\tnetworkid\x18\n \x01(\tb\x06proto3')
)




_TXS = _descriptor.Descriptor(
  name='Txs',
  full_name='Txs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txs', full_name='Txs.txs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=35,
)


_TX = _descriptor.Descriptor(
  name='Tx',
  full_name='Tx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_', full_name='Tx.from_', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='Tx.to', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Tx.amount', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='fee', full_name='Tx.fee', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='Tx.nonce', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Tx.signature', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='recovery', full_name='Tx.recovery', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='transitionSignature', full_name='Tx.transitionSignature', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='transitionRecovery', full_name='Tx.transitionRecovery', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
    _descriptor.FieldDescriptor(
      name='networkid', full_name='Tx.networkid', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=226,
)

_TXS.fields_by_name['txs'].message_type = _TX
DESCRIPTOR.message_types_by_name['Txs'] = _TXS
DESCRIPTOR.message_types_by_name['Tx'] = _TX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Txs = _reflection.GeneratedProtocolMessageType('Txs', (_message.Message,), dict(
  DESCRIPTOR = _TXS,
  __module__ = 'tx_pb2'
  # @@protoc_insertion_point(class_scope:Txs)
  ))
_sym_db.RegisterMessage(Txs)

Tx = _reflection.GeneratedProtocolMessageType('Tx', (_message.Message,), dict(
  DESCRIPTOR = _TX,
  __module__ = 'tx_pb2'
  # @@protoc_insertion_point(class_scope:Tx)
  ))
_sym_db.RegisterMessage(Tx)


# @@protoc_insertion_point(module_scope)
